### ISSUE TITLE
Format data to post to Queue

### ISSUE THREAD

**Issue by bwornom7** [acstech/doppler-events#10]

**Comment by mattsmith803** [comment]
Specifically we will need to format the gRPC messages into the format Kafka (or Kafka connect) requires

**Comment by PranavMin** [comment]
What format does Kafka accept?

**Comment by PranavMin** [comment]
If they take json we're golden, if not, there's definitely going to be a very easy way to to it.

**Comment by mattsmith803** [comment]
Just need to confirm current JSON formatting is what we need in Kafka
